const wikiData = {
  commands: [
    { title: "/home", description: "Teleport You To Your Home Location." },
    { title: "/spawn", description: "Teleports You To Spawn" },
    { title: "/warp", description: "Shows A List Of Warps You Can Use" },
    { title: "/back", description: "Teleports You To Your Last Location" },
    { title: "/sethome", description: "Sets Your Home To The Location You're Standing At" },
    { title: "/kit", description: "Shows A List Of Kits You Can Redeem" },
    { title: "/balance", description: "Checks Your Bank Balance" },
    { title: "/sb", description: "Toggles Scoreboard Visibility" },
    { title: "/uc menu", description: "Opens Cosmetic Menu" },
    { title: "/jobs browse", description: "Browse The Jobs Menu" },
    { title: "/tags", description: "Opens The Chat Tags Menu" },
    { title: "/ah", description: "View The Auction House" },
    { title: "/ah sell [value]", description: "Put The Item In Your Hand On The Auction House. Value Can Be Changed To Anything You Want." },
    { title: "/gsit", description: "Shows Animations/Emotes You Can Use" },
    { title: "/rtp", description: "Teleports You To A Random Location" },
    { title: "/rewards", description: "Opens Daily Rewards Menu" }

  ],
  mobs: [
    { title: "Zombie Horde", description: "Spawn a group of zombies." },
    { title: "Explosive Zombie", description: "Will explode on death, but you don't know that." },
    { title: "Sprinter Zombie", description: "Will run after you if you are in range." },
    { title: "Jumper Zombie", description: "Randomly jumps and will jump towards you." },
    { title: "Thrower Zombie", description: "Throws you up in the air and away." },
    { title: "Stealth Zombie", description: "Invisible but you can see on the ground that it follows you." },
    { title: "Skilled Zombie", description: "Can pull you and teleport randomly away, got a lot going on." },
    { title: "Charged Creeper", description: "Regular charged creeper but will make a big hole." },
    { title: "Undead Creeper", description: "Won't die on explode and will constantly explode until killed, only makes small holes." },
    { title: "Bluff Creeper", description: "A creeper that explodes flowers." },
    { title: "Sniper", description: "Equips armor and creates a sky rain of arrows." },
    { title: "Water Creature", description: "Spawns only in water—don't let it hit you." },
    { title: "Mother Phantom", description: "Huge phantom miniboss with a bossbar that spawns minions." },
    { title: "Sam The Snowman", description: "Insane angry snowman throwing snow, only spawns in snowy areas." },
    { title: "Enderman Teleporter", description: "Can spawn endermites when teleporting." },
    { title: "Ninja Zombie", description: "Performs jump attacks and slices you up." },
    { title: "Angry Wolf", description: "Spawns small wolves and howls to rally them." },
    { title: "Knight Clan", description: "Group of knights—kill the banner holder first." },
    { title: "End Witch", description: "Spawns in the End, shoots projectiles and gives bad effects." },
    { title: "Bomber", description: "Zombie that walks around dropping bombs." },
    { title: "Hardcore Pillager", description: "Increases damage when low on health." },
    { title: "Lava Cube", description: "Spawns magma blocks beneath it, only in the Nether." },
    { title: "End Zombie", description: "Spawns in the End with a custom head." },
    { title: "End Skeleton", description: "Spawns in the End with a custom head and warps." },
    { title: "Angry Bee", description: "Deadly one-hit bee—kill it before it hits you." },
    { title: "Tank", description: "Hardcore tank mob that's tough to kill." },
    { title: "Archer", description: "Skeleton that burst-shoots and creates a shield." },
    { title: "Creeper Ore Changer", description: "Turns basic blocks into ores." },
    { title: "Lucky Villager", description: "Rare spawn, gives Tier V loot on right-click." },
    { title: "End Blaze", description: "More like flying particles than a blaze." },
    { title: "Invisible Spider", description: "Spawns invisible spiders." },
    { title: "Tornado", description: "Spawns in the desert, pulls and damages players." },
    { title: "Poison Frog", description: "Spits poison and leaps at players." },
    { title: "Invisible Enderman", description: "Only eyes visible—like invisible spider." },
    { title: "Zombie Stunner", description: "Stuns mobs around it on death." },
    { title: "Zombie Scrambler", description: "Throws items on the ground away." },
    { title: "Rancie Pig", description: "Turns into zombie pig on death and attacks." },
    { title: "Drowned Shifter", description: "Tries to drown you in water." },
    { title: "Webber Spider", description: "Shoots webs at you." },
    { title: "Alien", description: "Spawns via meteorite hit." },
    { title: "3 Crystals", description: "Spawn in different worlds, reward or explode, may teleport." },
    { title: "Aggressive Strider", description: "Attacks and shoots players while on lava." },
    { title: "Shadow Caster", description: "Nether mob that transforms and blinds you." },
    { title: "Lifewisp Guardian", description: "Heals passive mobs and players, found in specific biomes." },
    { title: "Arid Marauder", description: "Desert mob that shoots damaging dust waves." },
    { title: "Invisible Cave Spider", description: "Only spawns in caves." },
    { title: "Zombie Cave Miner", description: "Can spawn TNT and despawn; may drop ingots if killed first." }
  ],
  features: [
    { title: "Land Claiming", description: "Protect your builds from griefing." },
    { title: "Player Shops", description: "Create and manage your own shops." }
  ],
  items: [
    { title: "Thunder Blade", description: "Summons lightning on hit." },
    { title: "Shadow Cloak", description: "Grants temporary invisibility." }
  ],
  faq: [
    { question: "How do I claim land?", answer: "Use the /claim command while holding a golden shovel." },
    { question: "How to teleport to other players?", answer: "Use /tpa <player> to send a request." }
  ]
};
